//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announce_Information
    {
        public string REGISTERED_PERSION { get; set; }
        public Nullable<System.DateTime> REGISTERED_DT { get; set; }
        public string UPDATED_PERSION { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
        public string EXCLUSIVEFG { get; set; }
        public string COPORATION_CODE { get; set; }
        public int ANNOUNCE_ID { get; set; }
        public System.DateTime SCHEDULE_DATE { get; set; }
        public Nullable<System.DateTime> POST_DATE { get; set; }
        public string SUBJECT { get; set; }
        public string CONTENTS { get; set; }
        public string RCV_COPO { get; set; }
        public string RCV_GRADE { get; set; }
        public string RCV_CLASS { get; set; }
        public string RCV_USER { get; set; }
        public string STATUS { get; set; }
    }
}
