//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coporation_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coporation_Master()
        {
            this.User_Master = new HashSet<User_Master>();
        }
    
        public string REGISTERED_PERSION { get; set; }
        public Nullable<System.DateTime> REGISTERED_DT { get; set; }
        public string UPDATED_PERSION { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
        public string EXCLUSIVEFG { get; set; }
        public string COPORATION_CODE { get; set; }
        public string COPORATION_NAME { get; set; }
        public string COPORATION_ADDRESS1 { get; set; }
        public string COPORATION_ADDRESS2 { get; set; }
        public string COPORATION_ADDRESS3 { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string SMTP_SERVER { get; set; }
        public string PASSWORD { get; set; }
        public string PORT_NO { get; set; }
        public string SSL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Master> User_Master { get; set; }
    }
}
