//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter_Master
    {
        public string REGISTERED_PERSION { get; set; }
        public Nullable<System.DateTime> REGISTERED_DT { get; set; }
        public string UPDATED_PERSION { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
        public string EXCLUSIVEFG { get; set; }
        public string COPORATION_CODE { get; set; }
        public string SYSTEM_CLASS { get; set; }
        public string CLASSFICATION { get; set; }
        public string CODE { get; set; }
        public string DATA_ITEM1 { get; set; }
        public string DATA_ITEM2 { get; set; }
        public string DATA_ITEM3 { get; set; }
        public string DATA_ITEM4 { get; set; }
        public string DATA_ITEM5 { get; set; }
    }
}
