//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Master
    {
        public string REGISTERED_PERSION { get; set; }
        public Nullable<System.DateTime> REGISTERED_DT { get; set; }
        public string UPDATED_PERSION { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
        public string EXCLUSIVEFG { get; set; }
        public string COPORATION_CODE { get; set; }
        public string STUDENT_ID { get; set; }
        public string NAME { get; set; }
        public string TAG_ID { get; set; }
        public string GRADE { get; set; }
        public string CLASS { get; set; }
        public string STATUS { get; set; }
        public string USER_ID { get; set; }
    }
}
