//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Master
    {
        public string REGISTERED_PERSION { get; set; }
        public Nullable<System.DateTime> REGISTERED_DT { get; set; }
        public string UPDATED_PERSION { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
        public string EXCLUSIVEFG { get; set; }
        public string COPORATION_CODE { get; set; }
        public string USER_ID { get; set; }
        public string PASSWORD { get; set; }
        public string CLASS { get; set; }
        public string EMAIL_ADDRESS1 { get; set; }
        public string EMAIL_LANGUAGE1 { get; set; }
        public string EMAIL_ADDRESS2 { get; set; }
        public string EMAIL_LANGUAGE2 { get; set; }
        public string EMAIL_ADDRESS3 { get; set; }
        public string EMAIL_LANGUAGE3 { get; set; }
        public string EMAIL_ADDRESS4 { get; set; }
        public string EMAIL_LANGUAGE4 { get; set; }
        public string EMAIL_ADDRESS5 { get; set; }
        public string EMAIL_LANGUAGE5 { get; set; }
    
        public virtual Coporation_Master Coporation_Master { get; set; }
    }
}
